mod_name = "Worldly Bounds"
mod_id = "worldly_bounds"
mod_group = "com.theendercore"
mod_version = "1.0.0"
mod_description = "Client side world borders"
github_repo = "theendercore/ClientBorders"
discord_invite = "https://discord.gg/KZ5Q364hEg"
authors = [ "TheEnderCore" ]
license = "MIT"
version_range = ">=1.21.1 <1.21.2"
